### PR TITLE
Feature control panel

### PR DESCRIPTION
**Pull request by jaredramirez**
yoooooooooooo

---
This change is [Reviewable](https://reviewable.io/reviews/parkn-co/parkn-mobile/5)

### CODE REVIEW

**Comment by ijsnow** [comment]
What is happening

**Comment by jaredramirez** [comment]
Thought I forgot to commit the last of my local changes, so closed it to add them only to realize that I already pushed them and that even if I hadn't I could push them anyways and the pr would've automatically updated

**Comment by ijsnow** [comment]
*[Parkn/src/actions/authentication.js, line 47 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUiLqaFaKrJIsGmNpY:-KZUiLqaFaKrJIsGmNpZ:bb71nyg) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/actions/authentication.js#L47)):*
> ```JavaScript
>     .catch((err) => {
>       let payload = err;
>       console.log('payload', payload);
> ```

Oops

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/components/Box.js, line 13 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUj8kun882pfwCnnfZ:-KZUj8kun882pfwCnnf_:bifknrr) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/components/Box.js#L13)):*
> ```JavaScript
> 
> const Box = ({marginHorizontal, marginVertical, style, children}: Props): React.Element<*> => {
>   let propStyles = {
> ```

What's the reasoning behind such a complicated prop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/components/OverlayMenu.js, line 75 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUk3SS8Z8xFdR3YAg-:-KZUk3STtFPIxBmQ-Y-1:b-3a6dmc) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/components/OverlayMenu.js#L75)):*
> ```JavaScript
>   }
> 
>   render() {
> ```

This component's methods are ordered kind of weird. It's purely opinion based but I know I and others like to keep a uniform organization. I usually do constructor, lifecycle methods, then any other methods, and the last is always render. I'm open to rearranging but I think we should definitely at least keep all the lifecycle methods together and in the general order that they will happen(yes yours are in the right order, just seperate)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/components/OverlayMenu.js, line 75 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUk3SS8Z8xFdR3YAg-:-KZUkoiga81Co7rw9THb:b-cheh93) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/components/OverlayMenu.js#L75)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

This component's methods are ordered kind of weird. It's purely opinion based but I know I and others like to keep a uniform organization. I usually do constructor, lifecycle methods, then any other methods, and the last is always render. I'm open to rearranging but I think we should definitely at least keep all the lifecycle methods together and in the general order that they will happen(yes yours are in the right order, just seperate)
</blockquote></details>

I guess if you really think about it render is in between will mount and will unmount, but I don't view it as a lifecycle method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/containers/ControlPanel.js, line 55 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUmImk_9jOqHMdg6fk:-KZUmIml4PpYscrLylSW:b-dp99ar) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/containers/ControlPanel.js#L55)):*
> ```JavaScript
> );
> 
> // Maybe shouldn't be containers because both just recieve props, and don't talk to store?
> ```

Components can just be made up of other components as well :) I agree. I also think that its a bit strange to have two components exported/defined in one file, but the first one is just a one liner so I understand

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/containers/ControlPanel.js, line 20 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUnHYztGktNxwUZBB6:-KZUnHYztGktNxwUZBB7:bcho6lf) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/containers/ControlPanel.js#L20)):*
> ```JavaScript
> };
> 
> const ControlHeaderContainer = ({user}: ControlHeaderProps): React.Element<*> =>
> ```

Is this the blue thing at the top of the control panel? 

https://github.com/parkn-co/parkn-design/blob/master/mobile/.exportedArtboards/parkn-mobile/Control%20Panel.png

If so, we have to keep in mind that this is intended to also be the search bar, so it will be more complex as we get further in. Will eventually need to be in its own file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[a discussion](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUobABmq2GBU4XsAws:-KZUobABmq2GBU4XsAwt:b2c2s6p) (no related file):*
Did you mean to leave all the sketch files in this repo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/package.json, line 20 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUpGljJhbok_9skYwJ:-KZUpGljJhbok_9skYwK:b4g1pct) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/package.json#L20)):*
> ```JSON
>     "react": "15.3.2",
>     "react-native": "0.35.0",
>     "react-native-swiper": "^1.5.4",
> ```

Did you mean to remove this dependency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/containers/ControlPanel.js, line 10 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUq5SFZ4yb2R9evxqi:-KZUq5SFZ4yb2R9evxqj:b8x720l) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/containers/ControlPanel.js#L10)):*
> ```JavaScript
>   Text,
> } from 'react-native';
> import Dimensions from 'Dimensions';
> ```

Is this not a part of the `react-native` module anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/containers/ControlPanel.js, line 71 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUqMFl8D5CHoJ-v1Dx:-KZUqMFl8D5CHoJ-v1Dy:b-cx5g00) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/containers/ControlPanel.js#L71)):*
> ```JavaScript
>     // i don't like this, maybe make ControlPanelContainer
>     // stateful and use onLayout to get the width?
>     width: (width * 3),
> ```

Why do you need to do this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[a discussion](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUobABmq2GBU4XsAws:-KZUylx4ruGt8GObOn1b:b95kl2d) (no related file):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

Did you mean to leave all the sketch files in this repo?
</blockquote></details>

nope, i'll remove them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[Parkn/package.json, line 20 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUpGljJhbok_9skYwJ:-KZUz4IxKC48fFqFNMtn:bt67gu4) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/package.json#L20)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

Did you mean to remove this dependency?
</blockquote></details>

i did mean too, will delete it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[Parkn/src/components/Box.js, line 13 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUj8kun882pfwCnnfZ:-KZUzJXQFgFgkWDVqUS_:b-ff1zx7) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/components/Box.js#L13)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

What's the reasoning behind such a complicated prop?
</blockquote></details>

I don't think it's super complicated. just a shorthand prop for adding margins, which(i think) we'll be using a decent amount due to the transparent/overlay design. I'm not super attached to them, and am game with removing them if you feel it's too much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[Parkn/src/components/OverlayMenu.js, line 75 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUk3SS8Z8xFdR3YAg-:-KZUznIMJwEHG5CGKAJo:b1i54vu) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/components/OverlayMenu.js#L75)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

I guess if you really think about it render is in between will mount and will unmount, but I don't view it as a lifecycle method
</blockquote></details>

I know what you mean. I've gotten into the habit of ordering my methods as they're listed on https://facebook.github.io/react/docs/react-component.html#the-component-lifecycle, it makes sense in my head. I don't have a huge preference either way, but we should def be consistent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[Parkn/src/containers/ControlPanel.js, line 10 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUq5SFZ4yb2R9evxqi:-KZV1bzliKkTcNNncT8B:b-g5zxid) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/containers/ControlPanel.js#L10)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

Is this not a part of the `react-native` module anymore?
</blockquote></details>

it is, i don't really know what the difference is but I think it makes more sense for it to be imported from rn so I'll change it to that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[Parkn/src/containers/ControlPanel.js, line 20 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUnHYztGktNxwUZBB6:-KZV1pu1FqUQRvtWi_ru:b98mn0m) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/containers/ControlPanel.js#L20)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

Is this the blue thing at the top of the control panel? 

https://github.com/parkn-co/parkn-design/blob/master/mobile/.exportedArtboards/parkn-mobile/Control%20Panel.png

If so, we have to keep in mind that this is intended to also be the search bar, so it will be more complex as we get further in. Will eventually need to be in its own file
</blockquote></details>

yeah, it is that blue thing. I'm going to go ahead move it to it's own file because u right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[Parkn/src/containers/ControlPanel.js, line 71 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUqMFl8D5CHoJ-v1Dx:-KZV2HMAOM4PQYnE_3TO:b-5ej03) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/containers/ControlPanel.js#L71)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

Why do you need to do this?
</blockquote></details>

ScrollViews need a defined width(or height depending on orientation). The benefit to doing it dynamically as the comment suggest is that we can add/remove content from the horizontal menu without worry about rendering the right size. Not sure if it's worth the work though, because it's not hard to update this style if/when a change is made

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[Parkn/src/actions/authentication.js, line 47 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUiLqaFaKrJIsGmNpY:-KZV2pabIOekv_5hf2hR:b-896fix) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/actions/authentication.js#L47)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

Oops
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[Parkn/src/containers/ControlPanel.js, line 55 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUmImk_9jOqHMdg6fk:-KZV39kt0rgYhjvAOJm4:b5zelov) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/containers/ControlPanel.js#L55)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

Components can just be made up of other components as well :) I agree. I also think that its a bit strange to have two components exported/defined in one file, but the first one is just a one liner so I understand
</blockquote></details>

I think both of these will eventually need to access to the store, for the search function of the bar and the filtering/user info of the menu. So i'll move them to separate files but keep them as children of the `container/ControlPanel` directory

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/components/Box.js, line 13 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUj8kun882pfwCnnfZ:-K_7nBRm8xJz8t2soPtk:b-bcrubb) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/components/Box.js#L13)):*
<details><summary><i>Previously, jaredramirez (Jared Ramirez) wrote…</i></summary><blockquote>

I don't think it's super complicated. just a shorthand prop for adding margins, which(i think) we'll be using a decent amount due to the transparent/overlay design. I'm not super attached to them, and am game with removing them if you feel it's too much.
</blockquote></details>

I think we'll want that but I was saying its complicated as in it can be either a number or a boolean. But yea its not a big deal thats fine. But I did notice that you use `let` to declare this variable. Once we get eslint working with our setup it would bark at you to use `const`. It looks like you usually use const so I assume you were setting it in an if statement before but changed and forgot to switch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/components/OverlayMenu.js, line 75 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUk3SS8Z8xFdR3YAg-:-K_7on_jm7vLFsybgVPO:bi2xf8d) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/components/OverlayMenu.js#L75)):*
<details><summary><i>Previously, jaredramirez (Jared Ramirez) wrote…</i></summary><blockquote>

I know what you mean. I've gotten into the habit of ordering my methods as they're listed on https://facebook.github.io/react/docs/react-component.html#the-component-lifecycle, it makes sense in my head. I don't have a huge preference either way, but we should def be consistent
</blockquote></details>

What would be the merged order of the merged lists from the updating and mounting sections? Idk I kind of like render at the very end. Where would you put all the other instance methods that we would create that aren't in the lifecycle methods?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[Parkn/src/containers/ControlPanel/Menu.js, line 71 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUqMFl8D5CHoJ-v1Dx:-K_7pkSYI8VK5dULD_Ld:b-dw3u8u) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/containers/ControlPanel/Menu.js#L71)):*
<details><summary><i>Previously, jaredramirez (Jared Ramirez) wrote…</i></summary><blockquote>

ScrollViews need a defined width(or height depending on orientation). The benefit to doing it dynamically as the comment suggest is that we can add/remove content from the horizontal menu without worry about rendering the right size. Not sure if it's worth the work though, because it's not hard to update this style if/when a change is made
</blockquote></details>

Hm. I guess this can be addressed when/if we start having issues with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[a discussion](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-K_7rsfiJi8_O15LLOu9:-K_7rsfjmN872t_WcTPW:bexgtkx) (no related file):*
I'm content with everything I see now. Let me run it real quick and mess around with it. Sorry it took me so long to get to this. 

Oh one more question, what was all the stuff changed in the Xcode project? Is it still going to work with the developer account/fabric setup I had?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
*[a discussion](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-K_7rsfiJi8_O15LLOu9:-K_7uhcMYn4zqlOzO-Qn:b-5zpbch) (no related file):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

I'm content with everything I see now. Let me run it real quick and mess around with it. Sorry it took me so long to get to this. 

Oh one more question, what was all the stuff changed in the Xcode project? Is it still going to work with the developer account/fabric setup I had?
</blockquote></details>

Dayum son works like a friggin charm coo coo cachooooooooooooooooooo!!!!!!!!!! lmao

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by ijsnow** [comment]
When does this check pass^^? I marked it as reviewed on reviewable. Go ahead and merge whenever you want @jaredramirez

**Comment by jaredramirez** [comment]
*[a discussion](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-K_7rsfiJi8_O15LLOu9:-K_8TASjgxmI5TPA0KAZ:b-xx0eux) (no related file):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

Dayum son works like a friggin charm coo coo cachooooooooooooooooooo!!!!!!!!!! lmao
</blockquote></details>

I'm not 100% sure, I still haven't really used fabric. I don't think it messed it up though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Comment by jaredramirez** [comment]
*[Parkn/src/components/OverlayMenu.js, line 75 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5#-KZUk3SS8Z8xFdR3YAg-:-K_8UFVhomjs-GuhhOfp:bvxu993) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/1de4eda51dc71e8b6c239d6525b0310f06280b5c/Parkn/src/components/OverlayMenu.js#L75)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary><blockquote>

What would be the merged order of the merged lists from the updating and mounting sections? Idk I kind of like render at the very end. Where would you put all the other instance methods that we would create that aren't in the lifecycle methods?
</blockquote></details>

I start with the constructor(if necessary) then `willMount`, `willReceiveProps`, `shouldUpdate`, `willUpdate`, then `render`, then `didUpdate` and `willUnmount`.  I'm changing it change it to the order of lifecycle methods,  render, instance methods for the time being.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/5)*

**Pull request merged**
