### PR TITLE
Feature testing

### PR DESCRIPTION
**Pull request by jaredramirez**
* Added a few new devDeps for testing, primarily jest
* Wrote unit tests for dumb components, actions, and reducers

Other notes:
basically the testing is centered around "snapshot testing". So the first time the tests run it creates a snapshot(assuming it ran correctly), and subsequent times it compares the output to the saved snapshot. Snapshots can be updated using the `yarn test -- -u` command.

---
This change is [Reviewable](https://reviewable.io/reviews/parkn-co/parkn-mobile/3)

### CODE REVIEW

**Comment by jaredramirez** [comment]
ALSO I didn't add any mock store or anything because I feel like the existing tests cover the logic pretty well and I'm tired of testing

**Comment by ijsnow** [comment]
*[Parkn/__tests__/actions/authentication.js, line 5 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3#-KX4Urb_wWTjkvxDl9r7:-KX4UrbaihueJGaKFELd:b-b3vm5m) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/202478ce0884eea9db1c8f2a7f47a7176ecd644c/Parkn/__tests__/actions/authentication.js#L5)):*
> ```JavaScript
> import 'react-native';
> import React from 'react';
> import { REHYDRATE } from 'redux-persist/constants';
> ```

Gaaaaaaaaaaaaaaaaaaaaahhhhh the spaces in the brackets!!!!! It burrrrrns!!!!!!!!!!!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3)*

**Comment by ijsnow** [comment]
*[Parkn/__tests__/actions/navigation.js, line 5 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3#-KX4V-VuZRCPqo_DLcxa:-KX4V-VuZRCPqo_DLcxb:b-a12uyh) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/202478ce0884eea9db1c8f2a7f47a7176ecd644c/Parkn/__tests__/actions/navigation.js#L5)):*
> ```JavaScript
> import 'react-native';
> import React from 'react';
> import { REHYDRATE } from 'redux-persist/constants';
> ```

Wheres yo linter at bro

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3)*

**Comment by ijsnow** [comment]
*[a discussion](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3#-KX4VLyxYa_GPhvHS1EY:-KX4VLyyw2UWwBIsooUR:biwjh4d) (no related file):*
So what are all the `.snap` files? They look autogenerated. If that's the case, are they something should they be checked in to git?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3)*

**Comment by ijsnow** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3#-:-KX6_xDF77USczhPU7V1:bnfp4nl)*

**Comment by jaredramirez** [comment]
*[a discussion](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3#-KX4VLyxYa_GPhvHS1EY:-KX6bj8zZ4P4qnb1pxGn:b3imv10) (no related file):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary>
> So what are all the `.snap` files? They look autogenerated. If that's the case, are they something should they be checked in to git?
</details>
the .snap files are generated. They might be better of not checked in, but because they're what the test output should be compared too it might be better for both of us to have the same test case. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3)*

**Comment by jaredramirez** [comment]
*[Parkn/__tests__/actions/authentication.js, line 5 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3#-KX4Urb_wWTjkvxDl9r7:-KX6cn1hjrAXb0hi1YjV:bj49azr) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/202478ce0884eea9db1c8f2a7f47a7176ecd644c/Parkn/__tests__/actions/authentication.js#L5)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary>
> Gaaaaaaaaaaaaaaaaaaaaahhhhh the spaces in the brackets!!!!! It burrrrrns!!!!!!!!!!!!
</details>
L O L I wish you could do bitmojis on here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3)*

**Comment by jaredramirez** [comment]
*[Parkn/__tests__/actions/navigation.js, line 5 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3#-KX4V-VuZRCPqo_DLcxa:-KX6dAwOX3CRsViLbdga:b67wff7) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/202478ce0884eea9db1c8f2a7f47a7176ecd644c/Parkn/__tests__/actions/navigation.js#L5)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary>
> Wheres yo linter at bro
</details>
YOOOOOOOOOOOOO only pulled in your linting changes at the end, and after the merge I didn't go though to update to the new rules.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3)*

**Comment by ijsnow** [comment]
*[a discussion](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3#-KX4VLyxYa_GPhvHS1EY:-KX6hyzB5vJrRlry31NN:b-7byrka) (no related file):*
<details><summary><i>Previously, jaredramirez (Jared Ramirez) wrote…</i></summary>
> the .snap files are generated. They might be better of not checked in, but because they're what the test output should be compared too it might be better for both of us to have the same test case. 
</details>
Soooo they don't get automatically generated each time you run a test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3)*

**Comment by ijsnow** [comment]
*[a discussion](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3#-KX4VLyxYa_GPhvHS1EY:-KX6iaBIG0nHCRG50_I-:bwp0sen) (no related file):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary>
> Soooo they don't get automatically generated each time you run a test?
</details>
Just did some brief reading. Looks like we do want to keep them around

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3)*

**Comment by ijsnow** [comment]
Reviewed 23 of 25 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/3)*

**Pull request merged**
