### PR TITLE
Flow and eslint shiz

### PR DESCRIPTION
**Pull request by ijsnow**
Ok so here is all the flow stuff I had. I'm dumb and stuff.

There are a bunch of places where we still have eslint errors. From here on out if we come across one in existing code we should go ahead and fix it. 

Some known issues:
We get [`no-extraneous-dependencies `](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) on packages in the dependencies folder. This is because eslint gets confused when we use nested `package.json`'s.
We also get [`no-use-before-define`](http://eslint.org/docs/rules/no-use-before-define) when `styles` is defined below the class. I can't figure out a workaround with this rule. Its generally a good thing but in this case I like styles to be at the bottom because they are the least important thing in the file IMO

---
This change is [Reviewable](https://reviewable.io/reviews/parkn-co/parkn-mobile/1)

### CODE REVIEW

**Comment by jaredramirez** [comment]
_[Parkn/src/components/Loading.js, line 27 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1#-KWiKYtrsl-m9gVNgQ61:-KWiKYtsT3P2SwBHCgdz:b-2xdf5e) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/ca016403f746bbb7d31b33dc7eef2ca61de26603/Parkn/src/components/Loading.js#L27)):_

> ``` JavaScript
> };
> 
> export default class Loading extends Component<Props, Props, State> {
> ```

Why do you have to specify `Props` twice when you extend component?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)_

**Comment by jaredramirez** [comment]
_[Parkn/src/containers/Navigation/NavBar.js, line 71 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1#-KWiOOyEHqluy5Lg1OQB:-KWiOOyEHqluy5Lg1OQC:b8yc7ff) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/ca016403f746bbb7d31b33dc7eef2ca61de26603/Parkn/src/containers/Navigation/NavBar.js#L71)):_

> ``` JavaScript
>             <Image
>               style={styles.titleIcon}
>               source={Images[route.titleIcon].source}
> ```

Images is declared as an empty object at the top of this file, I don't understand what it's being used for here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)_

**Comment by ijsnow** [comment]
_[Parkn/src/components/Loading.js, line 27 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1#-KWiKYtrsl-m9gVNgQ61:-KWiNn-5ugB2DM11rwa9:bbhq7qy) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/ca016403f746bbb7d31b33dc7eef2ca61de26603/Parkn/src/components/Loading.js#L27)):_
<details><summary>

<i>Previously, jaredramirez (Jared Ramirez) wrote…</i></summary>



> Why do you have to specify `Props` twice when you extend component?
> </details>
> When I was using nuclide it was yelling at me to add a config or something and it was `<Context, Props, State>` if I remember correctly. I was annoyed by it but did it to make it shut up. My new flow plugin for atom isn't. Not sure if thats good or not since facebook made flow and nuclide but I don't really like this syntax because you can specifiy props/state in the class definition. I just took this out and am going to take some more out then push some changes.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)_

**Comment by jaredramirez** [comment]
_[Parkn/src/flow-declarations/react.js, line 2 at r1](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1#-KWiP0O8dCgIQi_eF13F:-KWiP0O8dCgIQi_eF13G:bx56bo5) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/ca016403f746bbb7d31b33dc7eef2ca61de26603/Parkn/src/flow-declarations/react.js#L2)):_

> ``` JavaScript
> // @flow
> import React, {Component, Element} from 'react';
> ```

Do Component and Element need to be imported here?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)_

**Comment by jaredramirez** [comment]
Reviewed 3 of 47 files at r1.
Review status: 3 of 47 files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)_

**Comment by jaredramirez** [comment]
Reviewed 44 of 47 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)_

**Comment by jaredramirez** [comment]
*[Parkn/src/containers/Authentication/FormContainer.js, line 71 at r2](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1#-KX4IHRpboNUDEL0EQ8u:-KX4IHRpboNUDEL0EQ8v:bie83pc) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/e420f2e07878b4a7ec4b7d4386815e87450fb73a/Parkn/src/containers/Authentication/FormContainer.js#L71)):*
> ```JavaScript
>       this.setState(newState);
> 
>       return;
> ```

Necessary even though return type is void?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)*

**Comment by jaredramirez** [comment]
Reviewed 3 of 47 files at r1.
Review status: 38 of 49 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)*

**Comment by ijsnow** [comment]
*[Parkn/src/containers/Authentication/FormContainer.js, line 71 at r2](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1#-KX4IHRpboNUDEL0EQ8u:-KX4JwaIb0apF7nKWcV-:b12tudt) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/e420f2e07878b4a7ec4b7d4386815e87450fb73a/Parkn/src/containers/Authentication/FormContainer.js#L71)):*
<details><summary><i>Previously, jaredramirez (Jared Ramirez) wrote…</i></summary>
> Necessary even though return type is void?
</details>
Yep. Exit the function early if there are errors

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)*

**Comment by jaredramirez** [comment]
*[Parkn/src/containers/Authentication/FormContainer.js, line 71 at r2](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1#-KX4IHRpboNUDEL0EQ8u:-KX4KYOJW__NvUnwrfIx:bt53f8o) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/e420f2e07878b4a7ec4b7d4386815e87450fb73a/Parkn/src/containers/Authentication/FormContainer.js#L71)):*
<details><summary><i>Previously, ijsnow (Isaac Snow) wrote…</i></summary>
> Yep. Exit the function early if there are errors
</details>
Ah, though the bracket below was end of function, not end of if statement. My bad

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)*

**Comment by ijsnow** [comment]
*[Parkn/src/containers/Authentication/FormContainer.js, line 71 at r2](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1#-KX4IHRpboNUDEL0EQ8u:-KX4KnK9B_g5iLWmhHqp:b-clmevs) ([raw file](https://github.com/parkn-co/parkn-mobile/blob/e420f2e07878b4a7ec4b7d4386815e87450fb73a/Parkn/src/containers/Authentication/FormContainer.js#L71)):*
<details><summary><i>Previously, jaredramirez (Jared Ramirez) wrote…</i></summary>
> Ah, though the bracket below was end of function, not end of if statement. My bad
</details>
:100: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)*

**Comment by jaredramirez** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/parkn-co/parkn-mobile/1)*

**Pull request merged**
